### PR TITLE
Milestone 5: Design Teardown Project

### PR DESCRIPTION
**Pull request by ivanid22**
This is our finished version of the Design Teardown project. 

These are the sections of the final version:
 - Header
 - Articles sections
 - Ad space
 - Guides section
 - Footer

Please provide us with any feedback where necessary.
Thank you!

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review by Tolulope Olusakin(TSE) 
You have both done such an awesome job and I am currently writing your review, please check on it in 15 minutes :medal_military:

**Comment by nikasulo** [comment]
# Great job! @ivanid22 and @Cyrus-Kiprop 
This is too awesome! Wow, one of the neatest and best ones I've come across. You didn't treat the project as a waste of time and you really put your backs into it, paying a lot of attention to detail. This is very commendable.

Please make this one small change and request another review:
The center links need to be aligned to the center of the page like in the original site. 

Please amend that tiny detail and you are good to go!

**Comment by ivanid22** [comment]
Thank you very much for your input. We're going to be pushing the corrected code momentarily.

**Review by nikasulo — APPROVED** [review]
# Fantastic! @Cyrus-Kiprop and @ivanid22 
Please merge and keep going! :rocket:

**Comment by ivanid22** [comment]
Thank you very much again for your quick response.

**Pull request merged**
